### ISSUE TITLE
Prioritise existing MSF4J interceptors

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/msf4j#336]
Implement a mechanism to prioritise the existing interceptors so that interceptors would execute based on a certain order defined by the developer. Interceptors without a priority defined should have a default priority.

**Comment by denisrobert** [comment]
This is an absolute requirement, without which I cannot consider MSF4J production ready. Right now, the order is somewhat arbitrary, and postCalls are executed in the same order as preCalls (they need to be called in reverse order). The interceptors are stored as a List, so there's an implicit order defined so that if at least the postCall order were reversed, the implicit order would be useable. But right now you can't, for example, create a reliable security interceptor, since the post call for the security interceptor would be executed before post calls for later interceptors, so that the latter would no longer have access to the security context. This is at best counter-intuitive.

There's also an issue in Spring integration, where any bean of type Interceptor is automatically added, in whatever order Spring provides them in getBeansOfType. That has to be considered completely arbitrary, so it would only work for perfectly independent interceptors, which is certainly not the norm. The SpringMicroservicesRunner class needs to be modified to take @Order annotations into account.

**Comment by vidurananayakkara** [comment]
Hi @denisrobert,

Thank you for pointing this issue out and for your concerns regarding MSF4J.

This has been resolved and is under review currently. You can find the pull request at https://github.com/wso2/msf4j/pull/338

Please do note that we are not using the JAX-RS specification for prioritising. How to use interceptors and prioritising them could be found in the below articles.

**How to use MSF4J interceptors?**

General information could be found at:- https://github.com/vidurananayakkara/msf4j/blob/e8637502ff26e1898953f472ee88c74b80cdd446/samples/interceptor/README.md

Standalone jar mode:- https://github.com/vidurananayakkara/msf4j/blob/e8637502ff26e1898953f472ee88c74b80cdd446/samples/interceptor/fatjar-interceptor-service/README.md

Deployable jar mode:-
https://github.com/vidurananayakkara/msf4j/blob/e8637502ff26e1898953f472ee88c74b80cdd446/samples/interceptor/deployable-jar-interceptor-service/README.md

OSGi mode:-
https://github.com/vidurananayakkara/msf4j/blob/e8637502ff26e1898953f472ee88c74b80cdd446/samples/interceptor/osgi-interceptor-service/README.md

**Comment by vidurananayakkara** [comment]
Hi @denisrobert,

This has been fixed with #394. For prioritizing interceptors/filters and other interceptor related samples please refer [1].

[1] https://github.com/wso2/msf4j/blob/master/samples/interceptor/README.md

Thanks,
Vidura
